name = "OTS Experience"
author = "spheredev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e66fcf824f974c3fa73799f1c111fcc4e8852e74c3b577c0ac92dfa1ea1ee251"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21"]
