name = "OTS Experience"
author = "spheredev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "704d57e83a4ab96c486bb014aeb86b71e584453334a0b3cc67848bc94cd5823d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21"]
