name = "OTS Experience"
author = "spheredev"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3460c7b69775b6b72a35ade6397b05cb3fcaaae56a06955f564cfd9bcf186060"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21"]
